'use client';
import { ChangeEvent, useEffect, useMemo, useRef, useState } from 'react';
import Editor from './Editor'; import Viewport from './Viewport';
import { templates } from '@/lib/templates'; import { applyParameters, parseParameters } from '@/lib/scad'; import { projectStore } from '@/lib/storage'; import { Parameter } from '@/lib/types';

const download = (name: string, type: string, contents: string) => { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([contents], { type })); a.download = name; a.click(); URL.revokeObjectURL(a.href); };
export default function Studio() {
  const [templateId, setTemplateId] = useState('name-tag'); const active = useMemo(() => templates.find(t => t.id === templateId)!, [templateId]);
  const [source, setSource] = useState(active.source); const [parameters, setParameters] = useState<Parameter[]>(active.parameters); const [name, setName] = useState(active.name); const [saved, setSaved] = useState(''); const fileRef = useRef<HTMLInputElement>(null);
  const color = String(parameters.find(p => p.id === 'color')?.value || '#f59e0b');
  useEffect(() => { const timer = setTimeout(() => { setParameters(parseParameters(source, parameters)); }, 500); return () => clearTimeout(timer); }, [source]);
  function choose(id: string) { const t = templates.find(x => x.id === id)!; setTemplateId(id); setName(t.name); setSource(t.source); setParameters(t.parameters); }
  function updateParameter(id: string, value: Parameter['value']) { const next = parameters.map(p => p.id === id ? { ...p, value } : p); setParameters(next); setSource(applyParameters(source, next)); }
  function save() { const id = saved || crypto.randomUUID(); projectStore.save({ id, name, source, parameters, updatedAt: Date.now() }); setSaved(id); }
  function importScad(e: ChangeEvent<HTMLInputElement>) { const f = e.target.files?.[0]; if (!f) return; f.text().then(s => { setSource(s); setName(f.name.replace(/\.scad$/i, '')); setParameters(parseParameters(s, [])); }); }
  function batchCsv(e: ChangeEvent<HTMLInputElement>) { const f = e.target.files?.[0]; if (!f) return; f.text().then(text => { const [header, ...rows] = text.trim().split(/\r?\n/); const fields = header.split(','); const jobs = rows.filter(Boolean).map(row => Object.fromEntries(fields.map((k, i) => [k.trim(), row.split(',')[i]?.trim()]))); download('batch-jobs.json', 'application/json', JSON.stringify({ template: templateId, jobs }, null, 2)); }); }
  return <main className="studio"><header><div className="brand"><span>◒</span> CADENCE <small>STUDIO</small></div><div className="header-actions"><button className="quiet" onClick={() => fileRef.current?.click()}>Import .scad</button><input ref={fileRef} onChange={importScad} accept=".scad" hidden type="file" /><button className="quiet" onClick={save}>Save project</button><button className="primary" onClick={() => download(`${name}.scad`, 'text/plain', source)}>Export SCAD</button></div></header>
  <section className="workspace"><aside className="sidebar"><div className="side-title">TEMPLATES <span>+</span></div>{templates.map(t => <button key={t.id} onClick={() => choose(t.id)} className={`template ${t.id === templateId ? 'selected' : ''}`}><i>{t.icon}</i><span>{t.name}<small>{t.description}</small></span></button>)}<div className="side-footer"><b>OFFLINE READY</b><p>Your projects remain in this browser.</p></div></aside>
  <section className="canvas"><div className="canvas-toolbar"><span>Perspective</span><span className="grow" /><button>⊞ Fit</button><button>◫ Grid</button><button>↻ Reset</button></div><Viewport color={color} source={source} /></section>
  <aside className="inspector"><div className="panel-head"><span>PARAMETERS</span><button onClick={() => setParameters(parseParameters(source, parameters))}>↻</button></div><div className="fields">{parameters.map(p => <label key={p.id}>{p.label}<span>{p.kind === 'boolean' ? <input type="checkbox" checked={Boolean(p.value)} onChange={e => updateParameter(p.id, e.target.checked)} /> : p.kind === 'color' ? <input type="color" value={String(p.value)} onChange={e => updateParameter(p.id, e.target.value)} /> : <input type={p.kind === 'number' ? 'number' : 'text'} min={p.min} max={p.max} step={p.step} value={String(p.value)} onChange={e => updateParameter(p.id, p.kind === 'number' ? Number(e.target.value) : e.target.value)} />}</span></label>)}</div><div className="export"><b>MANUFACTURE</b><button onClick={() => download(`${name}.stl`, 'model/stl', 'solid placeholder\nendsolid placeholder\n')}>Export STL</button><button onClick={() => download(`${name}.3mf`, 'application/vnd.ms-package.3dmanufacturing-3dmodel+xml', source)}>Export 3MF</button><label className="csv">Batch from CSV<input type="file" accept=".csv" onChange={batchCsv} hidden /></label></div></aside></section>
  <section className="code"><div className="code-bar"><span><em /> {name}.scad</span><span>OpenSCAD compatible subset</span></div><Editor value={source} onChange={setSource} /></section><footer><span>READY</span><span>OpenCascade.js adapter: optional</span><span>{saved ? 'SAVED LOCALLY' : 'UNSAVED'}</span></footer></main>;
}
