import { Parameter } from './types';

export type Template = { id: string; name: string; icon: string; description: string; source: string; parameters: Parameter[] };
const common = (name: string): Parameter[] => [
  { id: 'text', label: 'Text', kind: 'text', value: name },
  { id: 'size', label: 'Font size', kind: 'number', value: 26, min: 8, max: 100, step: 1 },
  { id: 'thickness', label: 'Thickness', kind: 'number', value: 3, min: 1, max: 20, step: 0.5 },
  { id: 'color', label: 'Material color', kind: 'color', value: '#f59e0b' }
];
export const templates: Template[] = [
  { id: 'name-tag', name: 'Name Tag', icon: '✦', description: 'Personalized rounded badge', parameters: [...common('MAYA'), { id: 'hole', label: 'Key hole', kind: 'boolean', value: true }, { id: 'radius', label: 'Corner radius', kind: 'number', value: 5, min: 0, max: 25, step: 1 }], source: `// Name Tag — variables drive the control panel\ntext = "MAYA";\nfont_size = 26;\nthickness = 3;\nhole = true;\n\nmodule name_tag() {\n  difference() {\n    linear_extrude(thickness) offset(r=5) square([85, 35], center=true);\n    if (hole) translate([-34, 0, -1]) cylinder(h=thickness+2, r=3);\n  }\n  translate([0, 0, thickness]) linear_extrude(1) text(text, size=font_size, halign="center", valign="center");\n}\nname_tag();` },
  { id: 'keychain', name: 'Keychain', icon: '◌', description: 'A durable key ring fob', parameters: [...common('HELLO'), { id: 'hole', label: 'Ring hole', kind: 'number', value: 4, min: 2, max: 10, step: 0.5 }], source: `text = "HELLO";\nsize = 22;\nthickness = 4;\nhole = 4;\n\ndifference() {\n  linear_extrude(thickness) hull() { circle(15); translate([55,0]) circle(15); }\n  translate([-12,0,-1]) cylinder(h=thickness+2, r=hole);\n}\ntranslate([25,0,thickness]) linear_extrude(1) text(text, size=size, halign="center", valign="center");` },
  { id: 'sign', name: 'Sign', icon: '▭', description: 'Desk or wall sign', parameters: [...common('WELCOME'), { id: 'radius', label: 'Corner radius', kind: 'number', value: 4, min: 0, max: 25, step: 1 }], source: `text = "WELCOME";\nwidth = 140;\nheight = 55;\nthickness = 3;\n\nlinear_extrude(thickness) offset(r=4) square([width-8,height-8], center=true);\ntranslate([0,0,thickness]) linear_extrude(1) text(text, size=20, halign="center", valign="center");` },
  { id: 'box', name: 'Box', icon: '□', description: 'Parametric storage box', parameters: [{ id: 'size', label: 'Width', kind: 'number', value: 70, min: 20, max: 200, step: 1 }, { id: 'thickness', label: 'Wall thickness', kind: 'number', value: 2.4, min: 1, max: 10, step: .2 }, { id: 'color', label: 'Material color', kind: 'color', value: '#22c55e' }], source: `width = 70; depth = 50; height = 35; wall = 2.4;\ndifference() {\n  cube([width,depth,height]);\n  translate([wall,wall,wall]) cube([width-2*wall,depth-2*wall,height]);\n}` },
  { id: 'cookie-cutter', name: 'Cookie Cutter', icon: '♡', description: 'Custom cutter outline', parameters: [...common('LOVE'), { id: 'thickness', label: 'Wall thickness', kind: 'number', value: 1.2, min: .6, max: 4, step: .1 }], source: `text = "LOVE";\nheight = 15; wall = 1.2;\n// Replace this profile with a custom SVG outline\ndifference() {\n  linear_extrude(height) offset(r=wall) text(text, size=30, halign="center", valign="center");\n  translate([0,0,-1]) linear_extrude(height+2) offset(r=-wall) text(text, size=30, halign="center", valign="center");\n}` }
];
